import { Yeon_Sung, Nanum_Pen_Script } from "next/font/google";
import "./globals.css";
import MyHeader from "./components/MyHeader";
import AirportInfosProvider from "./AirportProvider";

const yeonSung = Yeon_Sung({
  weight: "400",
  subsets: ["latin"],
});

const nanum_Pen_Script = Nanum_Pen_Script({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sky Nap Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nanum_Pen_Script.className}>
        <AirportInfosProvider
          children={
            <div className="container">
              <MyHeader headText="비행기 낮잠 가이드" />
              {children}
            </div>
          }
        />
      </body>
    </html>
  );
}
