import { Yeon_Sung, Nanum_Pen_Script, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import MyHeader from "./components/MyHeader";
import AirportInfosProvider from "./AirportProvider";
import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

const yeonSung = Yeon_Sung({
  weight: "400",
  subsets: ["latin"],
});

const nanum_Pen_Script = Nanum_Pen_Script({
  weight: "400",
  subsets: ["latin"],
});

const noto_Sans_KR = Noto_Sans_KR({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sky Nap Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-DESYR520TS"
        ></Script>
        <Script id="google-analytics">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-DESYR520TS');
        `}
        </Script>
      </>
      <body>
        <AirportInfosProvider>
          <div className="container">
            <MyHeader headText="비행기 낮잠 가이드" />
            {children}
          </div>
        </AirportInfosProvider>
      </body>
      <GoogleTagManager gtmId="GTM-TFZ2VB2Q" />
    </html>
  );
}
