import { Yeon_Sung } from "next/font/google";
import "./globals.css";

const yeonSung = Yeon_Sung({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sky Nap Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={yeonSung.className}>{children}</body>
    </html>
  );
}
